default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: plamor_development
  username: wendellopes
  password: w2n1b1b2

test:
  <<: *default
  database: plamor_test
  username: wendellopes
  password: w2n1b1b2

production:
  <<: *default
  database: plamor_production
  username: wendellopes
  password: w2n1b1b2
